---
title: "Term Paper Report"
author: "Spencer Pease"
date: "6/09/2020"
output:
  pdf_document:
    latex_engine: xelatex
    highlight: tango
    df_print: kable
    fig_caption: true
    toc: true
    toc_depth: 2
    number_sections: true
abstract: "\\singlespacing `r paste0(readLines('abstract.txt'), collapse=' ')` \\newpage"
fontsize: 12pt
geometry: margin=1in
papersize: letter
header-includes:
  - \usepackage{setspace}
  - \onehalfspacing
---

\newpage

```{r setup, include=FALSE}

knitr::opts_chunk$set(
  echo = FALSE, warning = FALSE, message = FALSE,
  fig.width = 6.5, fig.height = 5
)
options(knitr.kable.NA = '-')

```

```{r prep, include=FALSE}

# Prep work ---------------------------------------------------------------

# Load libraries
library(ggplot2)

# Data

```

# Article Summary
# Methods Analysis & Implementation
# Methods Evaluation
# Discussion

\newpage

# Appendix

## References

Zhang, J.L. and Bryant, J. (2020). [Fully Bayesian Benchmarking of Small Area
Estimation Models][1]. _Journal of Official Statistics_ 36:197-223

[1]: https://content.sciendo.com/view/journals/jos/36/1/article-p197.xml

## Code

```{r getlabels, include=FALSE}
labs <- knitr::all_labels()
labs <- labs[!labs %in% c("setup", "toc", "getlabels", "allcode")]
```

```{r allcode, ref.label=labs, eval=FALSE, echo=TRUE}
```
