---
title: "Homework 06"
author: "Spencer Pease"
date: "5/18/2020"
output:
  pdf_document:
    latex_engine: xelatex
    highlight: tango
    df_print: kable
    fig_caption: true
---

```{r setup, include=FALSE}

gr <- 2 / (1 + sqrt(5))

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, fig.asp = gr)
options(knitr.kable.NA = '-')

rm(gr)
```

# Questions

```{r prep, include=FALSE}

# Prep work ---------------------------------------------------------------

# Load libraries
library(dplyr)
library(tidyr)
library(ggplot2)
library(bayesLife)

# Data
data("e0F", package = "wpp2019")
e0_sim_dir <- "./data/sim03092016"

# Control randomness
set.seed(9876)

```

## _Q1_

### _Q1.a_
### _Q1.b_
### _Q1.c_

## _Q2_

### _Q2.a_
### _Q2.b_
### _Q2.c_
### _Q2.d_

## _Q3_

### _Q3.a_
### _Q3.b_

## _Q4_

### _Q4.a_
### _Q4.b_
### _Q4.c_
### _Q4.d_
### _Q4.e_
### _Q4.f_
### _Q4.g_


# Appendix

```{r getlabels, include=FALSE}
labs <- knitr::all_labels()
labs <- labs[!labs %in% c("setup", "toc", "getlabels", "allcode")]
```

```{r allcode, ref.label=labs, eval=FALSE, echo=TRUE}
```
