---
title: "Homework 02"
author: "Spencer Pease"
date: "4/13/2020"
output:
  pdf_document:
    latex_engine: xelatex
    highlight: tango
    df_print: kable
    fig_caption: true
---

```{r setup, include=FALSE}

gr <- 2 / (1 + sqrt(5))

knitr::opts_chunk$set(echo = FALSE, fig.asp = gr)
options(knitr.kable.NA = '-')

rm(gr)
```

# Questions

```{r prep, include=FALSE}

# Prep work ---------------------------------------------------------------

# Load libraries
library(dplyr)
library(tidyr)
library(ggplot2)
library(wpp2019)

```


## _Q1_
### _Q1.a_
### _Q1.b_
### _Q1.c_
### _Q1.d_
### _Q1.e_
### _Q1.f_
### _Q1.g_
### _Q1.h_
### _Q1.i_

## _Q2_

```{r}

# Question 2 --------------------------------------------------------------

data(mxF)
thailand_mx <- mxF %>%
  filter(name == "Thailand") %>%
  select(age, Raw = `2015-2020`) %>%
  mutate(`Log-Transformed` = log(Raw)) %>%
  pivot_longer(-age, names_to = "scale", values_to = "mx")

```


### _Q2.a_

```{r, fig.dim=c(7, 6)}

# Question 2a -------------------------------------------------------------

thailand_mx_plot <- ggplot(thailand_mx, aes(x = age, y = mx)) +
  geom_point() +
  geom_line() +
  facet_wrap(vars(scale), nrow = 2, scales = "free_y") +
  theme_bw() +
  theme(text = element_text(family = "serif")) +
  labs(
    title = "Age-Specific Mortality Rates",
    subtitle = "Thailand, Females, 2015-2020",
    caption = "Source: WPP2019",
    x = "Age (years)",
    y = "Mortality Rate (mx and log(mx))"
  )

thailand_mx_plot

```

One unusual feature is...

### _Q2.b_
### _Q2.c_

## _Q3_
### _Q3.a_
### _Q3.b_
### _Q3.c_
### _Q3.d_
### _Q3.e_
### _Q3.f_
### _Q3.g_


# Appendix

```{r getlabels, include=FALSE}
labs <- knitr::all_labels()
labs <- labs[!labs %in% c("setup", "toc", "getlabels", "allcode")]
```

```{r allcode, ref.label=labs, eval=FALSE, echo=TRUE}
```
