---
title: "Homework 05"
author: "Spencer Pease"
date: "5/11/2020"
output:
  pdf_document:
    latex_engine: xelatex
    highlight: tango
    df_print: kable
    fig_caption: true
---

```{r setup, include=FALSE}

gr <- 2 / (1 + sqrt(5))

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, fig.asp = gr)
options(knitr.kable.NA = '-')

rm(gr)
```

# Questions

```{r prep, include=FALSE}

# Prep work ---------------------------------------------------------------

# Load libraries
library(dplyr)
library(tidyr)
library(ggplot2)
library(bayesTFR)

# Data
data("egsingle", package = "mlmRev")
data("tfr", package = "wpp2019")
tfr_sim_dir <- "./data/sim01192018"

tfr_all <- tfr %>%
  select(-country_code, -last.observed) %>%
  pivot_longer(-name, values_to = "tfr", names_pattern = "^(.*)-", names_to = "year")

# Control randomness
set.seed(9876)

```

## _Q1_

```{r}

# Question 1 --------------------------------------------------------------

edu_data <- egsingle %>% filter(year == .5)

```


### _Q1.a_
### _Q1.b_
### _Q1.c_
### _Q1.d_
### _Q1.e_

## _Q2_

```{r}

# Question 2 --------------------------------------------------------------

hnd_tfr <- tfr_all %>% filter(name == "Honduras") %>% select(-name)

```


### _Q2.a_
### _Q2.b_
### _Q2.c_

## _Q3_

```{r}

# Question 3 --------------------------------------------------------------

nld_tfr <- tfr_all %>% filter(name == "Netherlands") %>% select(-name)

```

### _Q3.a_
### _Q3.b_
### _Q3.c_

## _Q4_

```{r}

# Question 4 --------------------------------------------------------------

```

### _Q4.a_

```{r}

# Question 4.a ------------------------------------------------------------

tfr_mcmc  <- get.tfr.mcmc(tfr_sim_dir)
tfr3_mcmc <- get.tfr3.mcmc(tfr_sim_dir)
tfr_pred  <- get.tfr.prediction(tfr_sim_dir)

```


### _Q4.b_
### _Q4.c_


# Appendix

```{r getlabels, include=FALSE}
labs <- knitr::all_labels()
labs <- labs[!labs %in% c("setup", "toc", "getlabels", "allcode")]
```

```{r allcode, ref.label=labs, eval=FALSE, echo=TRUE}
```
